### ISSUE TITLE
Supplementary data files not provided

### ISSUE THREAD

**Issue by HengqiLiu** [Huber-group-EMBL/CITEseqLN-Tcells#3]
Dear professor
I cannot download the data you provided from the GEO repository because Supplementary data files not provided. I also didn't find it in the heiDATA repository.
Could you please fix this issue, we would like to include your cohort in our study and we will follow the requirements and rules.

Thanks.
Hengqi Liu

**Comment by wolfganghuber** [comment]
Dear Hengqi,
the data needed to be removed from GEO since they are private patient data who may legally only accessed by other researchers after approval by a data access committee that checks the terms of the informed consent.
If you could provide your institutional email, we can continue this discussion in that way, including with the clinical scientists who are in effect the data stewards. Then we can also discuss whether perhaps some summarized, public version of the data would already be sufficient for your purpose, which might be much faster and easier.

**Comment by dnfitzgerald** [comment]
Dear Hengqi,
The data is now accessible on the European Genome-Phenome Archive via study ID EGAS50000000342: https://ega-archive.org/studies/EGAS50000000342
I hope this is helpful.
Best,
Donnacha

**Comment by HengqiLiu** [comment]
Dear Professor Wolfgang and Donnacha,

I am very grateful that you have uploaded this data to the European Genome-Phenome Archive. I am also communicating with the data manager of our institute about this matter, and whether the public version of the summarized data meets our purpose. I may need some time to submit my application to our institution. 

Thanks again to you and your team.

Best,
Hengqi Liu

**Comment by dnfitzgerald** [comment]
Dear Hengqi,

We're happy to help. The uploaded data includes the sequencing data as fastq files and the downstream count tables as text files. Let us know if you have any more questions in the meantime.

Best wishes,
Donnacha

**Comment by HengqiLiu** [comment]
Dear Professor Donnacha，

Wow😄, I noticed that the data is already available for application, I have no other questions at the moment. 
Thank you for your patience. 

Best wishes,
Hengqi Liu
